#ifndef USBCONSTANTS_H
#define USBCONSTANTS_H

#define USB_BREQUEST_GET_EV 1
#define USB_BREQUEST_GET_RAW_TEMPERATURE 2
#define USB_BREQUEST_GET_RAW_LIGHT 3

#define USB_BREQUEST_GET_TEST_MSG 100

#endif
