#ifndef DISPLAY_CONSTANTS_H
#define DISPLAY_CONSTANTS_H

#define DISPLAY_DATA_PORT PORTB
#define DISPLAY_DATA_DDR  DDRB
#define DISPLAY_DATA_BIT  PB0
#define DISPLAY_CS_PORT   PORTB
#define DISPLAY_CS_DDR    DDRB
#define DISPLAY_CS_BIT    PB1
#define DISPLAY_CLK_PORT  PORTB
#define DISPLAY_CLK_DDR   DDRB
#define DISPLAY_CLK_BIT   PB2
#define DISPLAY_DC_PORT   PORTB
#define DISPLAY_DC_DDR    DDRB
#define DISPLAY_DC_BIT    PB4

#define DISPLAY_RESET_PORT PORTB
#define DISPLAY_RESET_DDR  DDRB
#define DISPLAY_RESET_BIT  PB3

#define DISPLAY_LCDWIDTH                  128
#define DISPLAY_LCDHEIGHT                 64

#define DISPLAY_SETCONTRAST 0x81
#define DISPLAY_DISPLAYALLON_RESUME 0xA4
#define DISPLAY_DISPLAYALLON 0xA5
#define DISPLAY_NORMALDISPLAY 0xA6
#define DISPLAY_INVERTDISPLAY 0xA7
#define DISPLAY_DISPLAYOFF 0xAE
#define DISPLAY_DISPLAYON 0xAF

#define DISPLAY_SETDISPLAYOFFSET 0xD3
#define DISPLAY_SETCOMPINS 0xDA

#define DISPLAY_SETVCOMDETECT 0xDB

#define DISPLAY_SETDISPLAYCLOCKDIV 0xD5
#define DISPLAY_SETPRECHARGE 0xD9

#define DISPLAY_SETMULTIPLEX 0xA8

#define DISPLAY_SETLOWCOLUMN 0x00
#define DISPLAY_SETHIGHCOLUMN 0x10

#define DISPLAY_SETSTARTLINE 0x40

#define DISPLAY_MEMORYMODE 0x20
#define DISPLAY_COLUMNADDR 0x21
#define DISPLAY_PAGEADDR   0x22

#define DISPLAY_COMSCANINC 0xC0
#define DISPLAY_COMSCANDEC 0xC8

#define DISPLAY_SEGREMAP 0xA0

#define DISPLAY_CHARGEPUMP 0x8D

#define DISPLAY_EXTERNALVCC 0x1
#define DISPLAY_SWITCHCAPVCC 0x2

#define DISPLAY_ACTIVATE_SCROLL 0x2F
#define DISPLAY_DEACTIVATE_SCROLL 0x2E
#define DISPLAY_SET_VERTICAL_SCROLL_AREA 0xA3
#define DISPLAY_RIGHT_HORIZONTAL_SCROLL 0x26
#define DISPLAY_LEFT_HORIZONTAL_SCROLL 0x27
#define DISPLAY_VERTICAL_AND_RIGHT_HORIZONTAL_SCROLL 0x29
#define DISPLAY_VERTICAL_AND_LEFT_HORIZONTAL_SCROLL 0x2A

#endif
